//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDePlanillas.Models.App_LocalResoures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDePlanillas.Models.App_LocalResoures.DescriptionError", typeof(DescriptionError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamadas ya procesadas en otra planilla.
        /// </summary>
        internal static string CallError1 {
            get {
                return ResourceManager.GetString("CallError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Débito no se encuentra registrado en el sistema.
        /// </summary>
        internal static string DebitError1 {
            get {
                return ResourceManager.GetString("DebitError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Tipo de Débito no se encuentra registrado en el sistema.
        /// </summary>
        internal static string DebitTypeError1 {
            get {
                return ResourceManager.GetString("DebitTypeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Asociado no se encuentra registrado en el sistema.
        /// </summary>
        internal static string EmployeeError1 {
            get {
                return ResourceManager.GetString("EmployeeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Asociado registrado en el sistema con el mismo  código CMS.
        /// </summary>
        internal static string EmployeeError2 {
            get {
                return ResourceManager.GetString("EmployeeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Asociado registrado en el sistema con la misma identificación.
        /// </summary>
        internal static string EmployeeError3 {
            get {
                return ResourceManager.GetString("EmployeeError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Asociado se encuentra deshabilitado.
        /// </summary>
        internal static string EmployeeError4 {
            get {
                return ResourceManager.GetString("EmployeeError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras no registrados en el sistema.
        /// </summary>
        internal static string ExtraError1 {
            get {
                return ResourceManager.GetString("ExtraError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Grupo de Operaciones no se enuentra registrado en el sistema.
        /// </summary>
        internal static string GroupError1 {
            get {
                return ResourceManager.GetString("GroupError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fechas proporcionadas son incorrectas..
        /// </summary>
        internal static string invalidDate {
            get {
                return ResourceManager.GetString("invalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha inicial contempla días ya procesador en la planilla anterior..
        /// </summary>
        internal static string invalidInitialDate {
            get {
                return ResourceManager.GetString("invalidInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar esta operación en el estado actual del sistema.
        /// </summary>
        internal static string invalidProcedure {
            get {
                return ResourceManager.GetString("invalidProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Sede no se encuentra registrada en el sistema.
        /// </summary>
        internal static string LocationError1 {
            get {
                return ResourceManager.GetString("LocationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Sede se encuentra deshabilitada.
        /// </summary>
        internal static string LocationError2 {
            get {
                return ResourceManager.GetString("LocationError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados producen valores negativos.
        /// </summary>
        internal static string negativeAmount {
            get {
                return ResourceManager.GetString("negativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La planilla no se encuentra registrada en el sistema.
        /// </summary>
        internal static string PayrollError1 {
            get {
                return ResourceManager.GetString("PayrollError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La penalización no se encuentra registrada en el sistema.
        /// </summary>
        internal static string PenaltyError1 {
            get {
                return ResourceManager.GetString("PenaltyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Penalización se encuentra deshabilidata.
        /// </summary>
        internal static string PenaltyError2 {
            get {
                return ResourceManager.GetString("PenaltyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de Penalización no se encuentra registrado en el sistema.
        /// </summary>
        internal static string PenlatyTypeError1 {
            get {
                return ResourceManager.GetString("PenlatyTypeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Role no se encuentra registrado en el sistema.
        /// </summary>
        internal static string RoleError1 {
            get {
                return ResourceManager.GetString("RoleError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Role ya cuenta con esta operación.
        /// </summary>
        internal static string RoleError2 {
            get {
                return ResourceManager.GetString("RoleError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Role registrado en el sistema con el mismo nombre.
        /// </summary>
        internal static string RoleError3 {
            get {
                return ResourceManager.GetString("RoleError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Role se encuentra deshabilidato.
        /// </summary>
        internal static string RoleError4 {
            get {
                return ResourceManager.GetString("RoleError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El conjunto de privilegios no se encuentra registrado en el sistema.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no se encuentra registrado en el sistema.
        /// </summary>
        internal static string UserError1 {
            get {
                return ResourceManager.GetString("UserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Usuario registrado en el sistema con la misma dirección de correo.
        /// </summary>
        internal static string UserError2 {
            get {
                return ResourceManager.GetString("UserError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Usuario registrado en el sistema con el nombre de usuario.
        /// </summary>
        internal static string UserError3 {
            get {
                return ResourceManager.GetString("UserError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se encuentra deshabilidato.
        /// </summary>
        internal static string UserError4 {
            get {
                return ResourceManager.GetString("UserError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La taza de interes no puede ser cero.
        /// </summary>
        internal static string zeroInterestRate {
            get {
                return ResourceManager.GetString("zeroInterestRate", resourceCulture);
            }
        }
    }
}
