//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDePlanillas.Models.App_LocalResoures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDePlanillas.Models.App_LocalResoures.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebitError1.
        /// </summary>
        internal static string debitInactive {
            get {
                return ResourceManager.GetString("debitInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeeError1.
        /// </summary>
        internal static string employeeInactive {
            get {
                return ResourceManager.GetString("employeeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkadministrator_location {
            get {
                return ResourceManager.GetString("fkadministrator_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError1.
        /// </summary>
        internal static string fkadministrator_user {
            get {
                return ResourceManager.GetString("fkadministrator_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fkcall_employee {
            get {
                return ResourceManager.GetString("fkcall_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollError1.
        /// </summary>
        internal static string fkcall_payroll {
            get {
                return ResourceManager.GetString("fkcall_payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fkdebit_employee {
            get {
                return ResourceManager.GetString("fkdebit_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebitTypeError1.
        /// </summary>
        internal static string fkdebit_type {
            get {
                return ResourceManager.GetString("fkdebit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebitError1.
        /// </summary>
        internal static string fkdebitpayment {
            get {
                return ResourceManager.GetString("fkdebitpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkdebittype_location {
            get {
                return ResourceManager.GetString("fkdebittype_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkemployee_location {
            get {
                return ResourceManager.GetString("fkemployee_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fkextra_employee {
            get {
                return ResourceManager.GetString("fkextra_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollError1.
        /// </summary>
        internal static string fklocation_currentpayroll {
            get {
                return ResourceManager.GetString("fklocation_currentpayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollError1.
        /// </summary>
        internal static string fklocation_lastpayroll {
            get {
                return ResourceManager.GetString("fklocation_lastpayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupError1.
        /// </summary>
        internal static string fkoperation {
            get {
                return ResourceManager.GetString("fkoperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkpayroll_location {
            get {
                return ResourceManager.GetString("fkpayroll_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError1.
        /// </summary>
        internal static string fkpayroll_user {
            get {
                return ResourceManager.GetString("fkpayroll_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fkpenalty_employee {
            get {
                return ResourceManager.GetString("fkpenalty_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollError1.
        /// </summary>
        internal static string fkpenalty_payroll {
            get {
                return ResourceManager.GetString("fkpenalty_payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PenaltyTypeError1.
        /// </summary>
        internal static string fkpenalty_type {
            get {
                return ResourceManager.GetString("fkpenalty_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkpenaltytype_location {
            get {
                return ResourceManager.GetString("fkpenaltytype_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkrole_location {
            get {
                return ResourceManager.GetString("fkrole_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fksalary_employee {
            get {
                return ResourceManager.GetString("fksalary_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollError1.
        /// </summary>
        internal static string fksalary_payroll {
            get {
                return ResourceManager.GetString("fksalary_payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string fksaving {
            get {
                return ResourceManager.GetString("fksaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string fkuser_location {
            get {
                return ResourceManager.GetString("fkuser_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError1.
        /// </summary>
        internal static string fkuser_role {
            get {
                return ResourceManager.GetString("fkuser_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebitError1.
        /// </summary>
        internal static string inexistentDebit {
            get {
                return ResourceManager.GetString("inexistentDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError1.
        /// </summary>
        internal static string inexistentEmployee {
            get {
                return ResourceManager.GetString("inexistentEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraError1.
        /// </summary>
        internal static string inexistentExtra {
            get {
                return ResourceManager.GetString("inexistentExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupError1.
        /// </summary>
        internal static string inexistentGroup {
            get {
                return ResourceManager.GetString("inexistentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string inexistentLocation {
            get {
                return ResourceManager.GetString("inexistentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PenaltyError1.
        /// </summary>
        internal static string inexistentPenalty {
            get {
                return ResourceManager.GetString("inexistentPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError1.
        /// </summary>
        internal static string inexistentRole {
            get {
                return ResourceManager.GetString("inexistentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError1.
        /// </summary>
        internal static string inexistentUser {
            get {
                return ResourceManager.GetString("inexistentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationError1.
        /// </summary>
        internal static string locationInactive {
            get {
                return ResourceManager.GetString("locationInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negativeAmount.
        /// </summary>
        internal static string negativeAmount {
            get {
                return ResourceManager.GetString("negativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PenaltyError1.
        /// </summary>
        internal static string penaltyInactive {
            get {
                return ResourceManager.GetString("penaltyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallError1.
        /// </summary>
        internal static string pkcall {
            get {
                return ResourceManager.GetString("pkcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError4.
        /// </summary>
        internal static string pkuser {
            get {
                return ResourceManager.GetString("pkuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError1.
        /// </summary>
        internal static string roleInactive {
            get {
                return ResourceManager.GetString("roleInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError2.
        /// </summary>
        internal static string RoleOperations_pkey {
            get {
                return ResourceManager.GetString("RoleOperations_pkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError4.
        /// </summary>
        internal static string roleWithUser {
            get {
                return ResourceManager.GetString("roleWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError2.
        /// </summary>
        internal static string ukemployee_cms {
            get {
                return ResourceManager.GetString("ukemployee_cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeError3.
        /// </summary>
        internal static string ukemployee_idcard {
            get {
                return ResourceManager.GetString("ukemployee_idcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleError3.
        /// </summary>
        internal static string ukrole_name {
            get {
                return ResourceManager.GetString("ukrole_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError2.
        /// </summary>
        internal static string ukuser_email {
            get {
                return ResourceManager.GetString("ukuser_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError3.
        /// </summary>
        internal static string ukuser_username {
            get {
                return ResourceManager.GetString("ukuser_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError1.
        /// </summary>
        internal static string userInactive {
            get {
                return ResourceManager.GetString("userInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zeroInterestRate.
        /// </summary>
        internal static string zeroInterestRate {
            get {
                return ResourceManager.GetString("zeroInterestRate", resourceCulture);
            }
        }
    }
}
